# Generated by Django 3.0.8 on 2020-07-18 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('Address', models.CharField(max_length=80)),
                ('PinCode', models.IntegerField(blank=True)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('ContactNo', models.BigIntegerField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='patientvitalinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodytemp', models.IntegerField(blank=True)),
                ('bpsys', models.IntegerField(blank=True)),
                ('bpdia', models.IntegerField(blank=True)),
                ('heartrate', models.IntegerField(blank=True)),
                ('breathingrate', models.IntegerField(blank=True)),
                ('dibetic', models.BooleanField(default=False)),
                ('alcoholic', models.BooleanField(default=False)),
                ('cigrate', models.BooleanField(default=False)),
                ('bloodglucose', models.IntegerField(blank=True)),
                ('oxygensaturation', models.IntegerField(blank=True)),
                ('other', models.CharField(blank=True, max_length=20)),
                ('other2', models.CharField(blank=True, max_length=20)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.PatientRecord')),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientSymtoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('occur_date', models.DateField(auto_now_add=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.PatientRecord')),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('problem', models.CharField(max_length=30)),
                ('problem_occur_date', models.DateField(auto_now_add=True)),
                ('problem_till_date', models.DateField(blank=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.PatientRecord')),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directions', models.CharField(max_length=200)),
                ('date_from', models.DateField(auto_now_add=True)),
                ('date_till', models.DateField(blank=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.PatientRecord')),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(max_length=30)),
                ('medicationcode', models.CharField(blank=True, max_length=30)),
                ('direction', models.CharField(max_length=60)),
                ('date_from', models.DateField(auto_now_add=True)),
                ('date_till', models.DateField(blank=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.PatientRecord')),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patientlab_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testdate', models.DateField(auto_now_add=True)),
                ('testname', models.CharField(max_length=60)),
                ('testreport', models.FileField(upload_to='Patientreports')),
                ('labid', models.IntegerField()),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.PatientRecord')),
            ],
        ),
        migrations.CreateModel(
            name='patientInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insurancecertificate', models.FileField(upload_to='insurance')),
                ('insurancecompany', models.CharField(max_length=25)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.PatientRecord')),
            ],
        ),
        migrations.CreateModel(
            name='PatientBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=1)),
                ('Fathers_id', models.BigIntegerField(blank=True)),
                ('Mathers_id', models.BigIntegerField(blank=True)),
                ('Bloodgroup', models.CharField(max_length=3)),
                ('dateofbirth', models.DateField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('profilepic', models.ImageField(blank=True, upload_to='userimage')),
                ('MarriedStatus', models.BooleanField(blank=True)),
                ('emergencyContact', models.BigIntegerField(blank=True)),
                ('Government_ID_Proof', models.IntegerField()),
                ('GovernmentIDNumber', models.CharField(max_length=18, unique=True)),
                ('Document', models.FileField(upload_to='')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.PatientRecord')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergyname', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('allergy_occur_date', models.DateField(auto_now_add=True)),
                ('allergy_till_date', models.DateField(blank=True)),
                ('allergy_level', models.CharField(max_length=5)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.PatientRecord')),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
