# Generated by Django 3.0.8 on 2020-07-18 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='billingdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofbilling', models.DateTimeField(auto_now_add=True)),
                ('billingpdf', models.FileField(upload_to='bills')),
                ('billname', models.CharField(max_length=25)),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.PatientRecord')),
            ],
        ),
    ]
