# Generated by Django 3.0.8 on 2020-07-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_dischargedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='Document',
            field=models.FileField(upload_to='govdocumentid'),
        ),
        migrations.AlterField(
            model_name='patientproblem',
            name='problem_till_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
