# Generated by Django 3.0.8 on 2020-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_patientvitalinfo_dateadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvitalinfo',
            name='bloodglucose',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientvitalinfo',
            name='bodytemp',
            field=models.FloatField(blank=True),
        ),
    ]
