# Generated by Django 3.0.8 on 2020-07-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_auto_20200720_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientallergy',
            name='dateadd',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='dateadd',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprescription',
            name='dateadd',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patientproblem',
            name='dateadd',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patientsymtoms',
            name='dateadd',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
