# Generated by Django 3.0.8 on 2020-07-21 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patient', '0011_auto_20200721_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patientdisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('disease', models.CharField(max_length=30)),
                ('disease_occur_date', models.DateField(auto_now_add=True)),
                ('disease_till_date', models.DateField(blank=True, null=True)),
                ('dateadd', models.DateTimeField(auto_now_add=True, null=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.PatientRecord')),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
