# Generated by Django 3.0.8 on 2020-07-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0012_patientdisease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='Bloodgroup',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='Document',
            field=models.FileField(null=True, upload_to='govdocumentid'),
        ),
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='Fathers_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='GovernmentIDNumber',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='Government_ID_Proof',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='MarriedStatus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='Mathers_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='emergencyContact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='userimage'),
        ),
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
