# Generated by Django 3.0.8 on 2020-08-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0013_auto_20200730_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='profilepic',
            field=models.ImageField(blank=True, default='userimage/default-user-icon.png', null=True, upload_to='userimage'),
        ),
    ]
