# Generated by Django 3.0.8 on 2020-07-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_auto_20200719_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalcircle',
            name='otp',
            field=models.CharField(default=387702, max_length=20),
        ),
    ]
