# Generated by Django 3.0.8 on 2020-07-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_auto_20200720_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalcircle',
            name='otp',
            field=models.CharField(default=881278, max_length=20),
        ),
    ]
