# Generated by Django 3.0.8 on 2020-07-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0012_patientdisease'),
        ('Hospital', '0012_auto_20200721_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalcircle',
            name='otp',
            field=models.CharField(default=778498, max_length=20),
        ),
        migrations.CreateModel(
            name='LabCircle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(default=339528, max_length=20)),
                ('accepted', models.BooleanField(default=False)),
                ('Timeofjoin', models.DateTimeField(blank=True)),
                ('Labref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.lab')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Patient.PatientRecord')),
            ],
        ),
    ]
