# Generated by Django 3.0.8 on 2020-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0014_auto_20200724_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalcircle',
            name='otp',
            field=models.CharField(default=131621, max_length=20),
        ),
        migrations.AlterField(
            model_name='labcircle',
            name='otp',
            field=models.CharField(default=635366, max_length=20),
        ),
    ]
