# Generated by Django 3.0.8 on 2020-07-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0015_auto_20200724_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_staff_records',
            name='date_of_joining',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalcircle',
            name='otp',
            field=models.CharField(default=863672, max_length=20),
        ),
        migrations.AlterField(
            model_name='labcircle',
            name='otp',
            field=models.CharField(default=160976, max_length=20),
        ),
    ]
