# Generated by Django 3.0.8 on 2020-07-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0016_auto_20200726_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalcircle',
            name='otp',
            field=models.CharField(default=944251, max_length=20),
        ),
        migrations.AlterField(
            model_name='labcircle',
            name='otp',
            field=models.CharField(default=512105, max_length=20),
        ),
    ]
