# Generated by Django 3.0.8 on 2020-08-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0017_auto_20200730_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalcircle',
            name='otp',
            field=models.CharField(default=766425, max_length=20),
        ),
        migrations.AlterField(
            model_name='labcircle',
            name='otp',
            field=models.CharField(default=420192, max_length=20),
        ),
    ]
